apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      -image: adebeco/audio-diarization:v1
        name: api
        ports:
        -containerPort: 5901
          name: http
        env:
        -name: API_KEY
          value: "4a6e07d289e10d710761fae2288b3b69"